name: MSBuild with Caching and Artifacts

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFI"GURATION: Release
  VCPKG_DIR: ${{ runner.tool_cache }}/vcpkg"
  ASSETS_PATH: 'Assets' # Relative path from the root of your repository

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    # Cache vcpkg installed packages
    - name: Cache vcpkg packages
      uses: actions/cache@v3
      with:
        path: ${{env.VCPKG_DIR}}
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Set up vcpkg
      run: |
        if not exist "${{env.VCPKG_DIR}}" (
          git clone https://github.com/Microsoft/vcpkg.git ${{env.VCPKG_DIR}}
          .\vcpkg\bootstrap-vcpkg.bat
        )

    - name: Install dependencies with vcpkg
      run: |
        .\vcpkg\vcpkg install
        .\vcpkg\vcpkg integrate install

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build with MSBuild
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          D:\a\dxagain\dxagain\x64\Release\**
          ${{github.workspace}}/${{env.ASSETS_PATH}}/**
